### ISSUE TITLE
Feature - Fazer um PR Template

### ISSUE THREAD

**Issue by Hiroshi18** [deeplearningunb/review_analyzer#3]
**Sua feature é relacionado com um problema? Por favor descreva.**
Nos não temos um template para realizar PR

**Descreva a solução que vc gostaria**
Um template Legal para PR's

**Comment by lorryaze** [comment]
Fiz o template porém precisa ser melhorado.

**Comment by Hiroshi18** [comment]
Vou dar uma olhada e melhorar ele
